services:
  - type: web
    plan: free
    name: PYRO-RENAME-BOT
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/MrMKN/Simple-Rename-Bot.git
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: DOWNLOAD_LOCATION
        sync: false
      - key: ADMIN
        sync: false
      - key: CAPTION
        sync: false
        
